routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Route::get('to/{locale}', function ($locale) {
    App::setLocale($locale);
});

Route::get('/', 'PageController@home')->name('home');
Route::get('/espacios', 'PageController@spaces')->name('spaces');
Route::get('/fonoteca', 'PageController@soundLibrary')->name('sound-library');
Route::get('/eventos', 'PageController@events')->name('events');
Route::get('/museo', 'PageController@museum')->name('museum');
Route::get('/palacio', 'PageController@palacio')->name('palacio');
Route::get('/transparencia', 'PageController@trans')->name('trans');
Route::get('/contacto', 'PageController@contact')->name('contact');
Route::post('/contacto', 'PageController@contactPost')->name('contact.post');
Route::get('/tour', 'PageController@tour')->name('tour');
Route::post('/tour', 'PageController@tourPost')->name('tour.post');
// Route::get('/directorio', 'PageController@directory')->name('directory');
Route::get('/contabilidad/{year?}/{month?}', 'PageController@accounting')->name('accounting');

// Route::get('mailable', function () {
//     $data = [
//         'fullname' => 'Lorem, ipsum dolor.',
//         'email' => 'email@foo.com',
//         'subject' => 'Subject: Lorem, ipsum.',
//         'message' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita, placeat et quibusdam laudantium assumenda aut!',
//     ];

//     return new App\Mail\ContactForm($data);
// });

Route::get('/{section}/{page?}', 'PageController@post')->name('post')->where('section', '^(?!nova.*$)[0-9a-z\-]+');

app/Period.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Period extends Model
{
    protected $appends = ['name', 'month_name'];

    public function getNameAttribute()
    {
        return "{$this->year} / {$this->month}";
    }

    public function getMonthNameAttribute()
    {
        return Carbon::parse("{$this->year}-{$this->month}-1 ")->monthName;
    }

    public function getTrimesterNameAttribute()
    {
        return $this->getTrimesterName($this->month);
    }

    private function getTrimesterName($month)
    {
        if ($month >= 1 && $month < 4) {
            return '1er Trimestre';
        } elseif ($month >= 4 && $month < 7) {
            return '2o Trimestre';
        } elseif ($month >= 7 && $month < 10) {
            return '3er Trimestre';
        } elseif ($month >= 10 && $month <= 12) {
            return '4o Trimestre';
        }
        return '';
    }
}

resources/views/accounting.blade.php
@extends('layouts.app')

@section('tail')
<script>
        var dropdowns = document.getElementsByClassName('dropdown');

        for (let i = 0; i < dropdowns.length; i++) {
                dropdowns[i].addEventListener("click", function () {
                        console.log("Clicked index: " + i);
                        if (this.parentNode.classList.contains('show')) {
                                this.parentNode.classList.remove('show');
                        } else {
                                this.parentNode.classList.add('show');
                        }
                })
        }

</script>
@endsection



@section('header')
<header class="h-100 bg-cover bg-no-repeat bg-center" style="background-image: url({{url('storage/images/slidePalacioMusica-01.jpg')}})"></header>
@endsection
@section('content')
<section class="container mx-auto pt-6 pb-8">
        <h2 class=" mx-6 text-2xl text-palam-500 uppercase"> <a href="{{route('accounting',['year'=>$year])}}">Contabilidad Gubernamental </a> </h2>
        <div class="mx-6 my-6 flex antialiased">
                <div class="flex flex-col w-32 ">
                        <div class="dropdown flex items-center justify-between text-lg font-semibold bg-palam-500 text-white py-1 px-2 cursor-pointer">
                                Año
                                @svg('chevron-down','fill-current text-white h-3 mr-2',[])
                        </div>
                        <div class="item absolute w-32 mt-8 shadow-lg">
                                @foreach($years as $y)
                                <div class="bg-palam-700 text-white pt-1 px-2 "> <a href="{{route('accounting',['year'=>$y])}}" class="block">{{$y}}</a> </div>
                                @endforeach
                        </div>
                </div>
                <div class="flex flex-col w-32 ml-6">
                        <div class="dropdown flex items-center justify-between text-lg font-semibold bg-palam-500 text-white py-1 px-2 cursor-pointer">

                                Mes
                                @svg('chevron-down','fill-current text-white h-3 mr-2',[])
                        </div>
                        <div class="item absolute w-32 mt-8 shadow-lg">
                                @foreach($periods as $p)
                                <div class="bg-palam-700 text-white  pt-1 px-2 ">
                                        <a href="{{route('accounting',['year'=>$p->year,'month'=>$p->month])}}" class="block capitalize">@if($p->trimester){{$p->trimester_name}}@else{{$p->month_name}}@endif</a>
                                </div>
                                @endforeach
                        </div>
                </div>
        </div>
        @if(is_null($month))

        <ol class="flex flex-col lg:flex-row lg:flex-wrap justify-around">
                @foreach($periods as $p)
                <li class="lg:w-5/12 bg-palam-100 mx-4 mt-4 antialiased">
                        <a href="{{route('accounting',['year'=>$p->year,'month'=>$p->month])}}" class="py-4 px-6 text-white block capitalize">{{$p->month_name}}</a>
                </li>
                @endforeach
        </ol>
        @else
        <h4 class="mx-6 my-4 font-semibold text-2xl text-palam-500 uppercase">{{$period->month_name}} {{$year}}</h4>
        <div class="flex flex-col justify-around lg:flex-row items-start mx-6">
                @foreach($categories as $c)
                <div class="mb-4">
                        <div class="text-palam-500 font-bold uppercase  ">{{$c->name}}</div>
                        <ol class="flex flex-col">
                                @forelse($c->reports($year,$month)->get() as $r)
                                <li class="ml-4 py-1">
                                        <a class="hover:text-palam-100" href="{{url("storage/{$r->filename}")}}" download>{{$r->name}}</a>
                                </li>
                                @empty
                                <li class="ml-4 py-1 text-gray-500">
                                        No hay reportes disponibles
                                </li>
                                @endforelse
                        </ol>
                </div>
                @endforeach
        </div>
        @endif
</section>


@endsection

resources/views/contact.blade.php
@extends('layouts.app')

@section('header')
<header class="bg-bottom bg-no-repeat bg-cover h-100" style="background-image: url({{url('storage/images/slidePalacioMusica.jpg')}})">
</header>
<head>
   {!! NoCaptcha::renderJs() !!}
</head>
@endsection

@section('content')
<section class="container mx-auto">
    <div class="flex flex-col items-start justify-between px-6 pt-8 lg:flex-row">
        <div class="flex-1">
            <h1 class="text-2xl uppercase text-palam-500">Contáctanos</h1>
            <p class="mt-4 text-gray-800">
                {!!setting('direccion','Calle 58 núm. 497 x 59 y 60, <br/>Centro Histórico, <br/>Mérida, Yucatán.',true)!!}
            </p>
            <p class="mt-4 text-gray-800">
                <h4>Horarios</h4>
                <div class="whitespace-pre-line"> {{setting('horario','Martes a domingo de 10:00 a.m. a 4:00 p.m.')}} </div>
            </p>
            <p class="mt-4 text-gray-800">
                <a href="mailto:{{setting('contact-email','contactopdlm@yucatan.gob.mx')}}">{{setting('contact-email','contactopdlm@yucatan.gob.mx')}}</a>
            </p>
            <p class="mt-4">
                <a href="http://www.yucatan.gob.mx/gobierno/detalle.php?id_d=87" class="btn btn-primary">Directorio</a>
            </p>
        </div>
        <div class="flex-1 w-full mt-8 lg:mt-0">
            @if(isset($message))
            <div class="px-3 py-2 my-4 text-center text-orange-100 bg-orange-500 rounded">
                {{$message}}
            </div>
            @endif
            <form action="{{route('contact')}}" method="POST">
                @csrf
                <div>
                    <div class="text-gray-700">Nombre</div>
                    <div>
                        <input name="fullname" class="border border-2 border-palam-500 appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500
                            type=" text">
                    </div>
                </div>
                <div>
                    <div class="text-gray-700">Correo Electrónico</div>
                    <div>
                        <input name="email" class="border border-2 border-palam-500 appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500
                            type=" email">
                    </div>
                </div>
                <div>
                    <div class="text-gray-700">Asunto</div>
                    <div>
                        <input name="subject" class="border border-2 border-palam-500 appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500
                            type=" text">
                    </div>
                </div>

                <div class="mt-4">
                    <div class="text-gray-700">Mensaje</div>
                    <div><textarea name="message" class="h-24 border border-2 border-palam-500 appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500
                            name="" id="" cols=" 30" rows="10"></textarea></div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6 offset-md-4">
                        {!! NoCaptcha::display() !!}
                    </div>
                </div>
                @if ($errors->has('g-recaptcha-response'))
                    <span class="text-red-700 help-block" role="alert">
                        <strong>Completar recaptcha</strong>
                    </span>
                @endif
                <div class="mt-4 mb-8 text-right">
                    <button class="btn btn-primary" type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</section>
<div class="border-t-4 border-palam-500">
    <iframe class="w-full h-64" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14902.40810700236!2d-89.6215745!3d20.9684914!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xfe685b8e8345c314!2sPalacio%20de%20la%20M%C3%BAsica!5e0!3m2!1sen!2smx!4v1581096454384!5m2!1sen!2smx" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
</div>
@endsection

resources/views/events.blade.php
@extends('layouts.app')

@section('header')
<header class="h-100 bg-cover bg-no-repeat bg-center" style="background-image: url({{url('storage/images/slidePalacioMusica-01.jpg')}})"></header>
@endsection

@section('content')
<div class="absolute mt-20 z-10 w-full">
    <div id="popup" class="popup-fixed hidden bg-palam-500 text-gray-100  shadow-lg">
        <div class="float-right text-4xl w-8 h-8 mr-2 cursor-pointer hover:text-gray-400" onclick="closePopup('popup')">&times;</div>
        <div class="py-8">
            <div class="flex justify-between">
                <h2 id="popup-title" class="mx-16 mb-4 text-2xl tracking-wide uppercase font-semibold">Lorem ipsum dolor sit amet.</h2>
            </div>
            <div class="flex flex-col lg:flex-row justify-between mx-16 ">
                <div class="w-full pb-2 lg:w-1/3 lg:pb-0">
                    <img id="popup-photo" class="w-full lg:h-64 lg:w-64 object-cover" src='http://unsplash.it/300/300?random' alt='' />
                </div>
                <div id="popup-content" class="pl-4 w-2/3">
                    <p class="whitespace-pre-line">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.

                        Obcaecati, ipsam explicabo molestiae tempora ducimus unde? Dolor adipisci esse possimus, nobis ab tenetur commodi ullam rem
                        saepe maxime impedit autem quo laboriosam cumque odit. Rem, veniam.
                    </p>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="container mx-auto pt-6 pb-8 px-6">
    <div class="py-8">
        <h1 class="font-bold text-palam-500 text-xl uppercase">Eventos</h1>
        @forelse($spaces as $space)
        <div class="my-8">
            <h2 class="text-lg font-semibold text-palam-500">{{$space->name}}</h2>
            <div class="flex mt-4">
                @forelse($space->events()->active()->orderBy('expires_on','desc')->get() as $event)
                <div class="ml-4 first:ml-0">
                    <a href='javascript:openPopup(JSON.stringify({!!$event!!}))'>
                    <img class="object-cover w-64 h-64" src="{{asset('storage/'.$event->photo_url)}}" alt="{{$event->title}}"></a>
                    <p class="mt-4">
                        <a href='javascript:openPopup(JSON.stringify({!!$event!!}))'>{{$event->title}}</a>
                    </p>
                </div>
                @empty
                No hay eventos proximos
                @endforelse
            </div>
            @empty
            No hay eventos por el momento.
        </div>
        @endforelse
    </div>

</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('header')

<header class="h-100  bg-cover bg-no-repeat bg-bottom" style="background-image: url({{url('storage/images/slidePalacioMusica-01.jpg')}})">
    <div class="absolute flex h-56 md:h-auto flex-col w-full sm:w-2/3 md:w-1/2 lg:w-2/5 h-48 p-4 mt-40 ml-0 xs:ml-8 md:ml-32 lg:ml-48 xl:ml-64 bg-palam-nav">
        <h2 class="font-bold text-white uppercase">La Música Mexicana</h2>
        <p class="text-white mt-2">
        La música en México es rica en variedad de géneros ritmos y temas.
        Es fruto del mestizaje entre tradiciones y tiene profundas raíces de
        lo prehispánico.
        </p>
        <!-- <p class="text-white mt-2">
            La música en México es rica en variedad de géneros, ritmos y temas. Es fruto del mestizaje entre las
            tradiciones europea y americana, pero tiene profundas raíces de lo prehispánico y de nuestra tercera raíz,
            que aunque poco reconocida en otros ámbitos culturales es en la música donde adquiere mayor relevancia.
        </p> -->
    </div>
</header>

@endsection

@section('content')


<div class="container mx-auto">
    <div class="py-8">
        <div class="flex flex-col md:flex-row justify-center">
            <div class="flex-1 mx-4">
                <a href="{{route('events')}}">
                    <img class="mb-2 h-64 object-cover" src="{{asset('storage/images/EVENTOS.JPG')}}" alt="Eventos">
                </a>
                <div>
                    <h2 class="my-4 text-lg font-semibold text-palam-500 uppercase">
                        <a href="{{route('events')}}"> Eventos </a>
                    </h2>
                    <p class="antialiased">Consulta los próximos conciertos, talleres y actividades.</p>
                </div>
            </div>
            <div class="flex-1 mx-4">
                <a href="{{route('museum')}}">
                    <img class="mb-2 h-64 object-cover" src="{{asset('storage/images/MUSEO INTERACTIVO.JPG')}}" alt="Museo Interactivo">
                </a>
                <div>
                    <h2 class="my-4 text-lg font-semibold text-palam-500 uppercase">
                        <a href="{{route('museum')}}">
                            Museo Interactivo
                        </a>
                    </h2>
                    <p class="antialiased">Realiza un recorrido por la historia de la música tradicional y popular mexicana.</p>
                </div>
            </div>
            <div class="flex-1 mx-4">
                <a href="{{route('spaces')}}">
                    <img class="mb-2 h-64 object-cover" src="{{asset('storage/images/ESPACIOS Y SERVICIOS.jpg')}}" alt="Espacios y Servicios">
                </a>
                <div class="">
                    <h2 class="my-4 text-lg font-semibold text-palam-500 uppercase">
                        <a href="{{route('spaces')}}"> Espacios y Servicios</a> </h2>

                    <p class="antialiased">Descubre los distintos espacios y servicios dedicados al conocimiento y disfruta del patrimonio musical de México.</p>
                </div>
            </div>
        </div>
        <div class="mt-10 bg-palam-100 flex flex-col flex-col-reverse md:flex-row md">
            <div class="flex-1 px-20 py-12">
                <h4 class="text-lg font-semibold text-palam-500 uppercase ">Recorridos Escolares Gratuitos</h4>
                <p class="mt-8">Dirigidos a grupos educativos integrados por estudiantes escolares o universitarios y sus profesores.</p>
                <a class="mt-8 inline-block btn btn-primary" href="{{route('tour')}}">Solicita recorrido</a>
            </div>
            <div class="flex-1">
                <img class="" src="{{asset('storage/images/IGH-96.png')}}" alt="">
            </div>
        </div>
        <div class="flex flex-col md:flex-row mt-8">
            <div class="flex-1">
                <img class="" src="{{asset('storage/images/TARIFAS.JPG')}}" alt="">
            </div>
            <div class="flex-1 ml-6 text-gray-800">
                <h5 class="text-palam-500 font-semibold text-lg uppercase mt-4 md:mt-0"> TARIFAS </h5>
                <p class="uppercase font-semibold">Museo Interactivo</p>
                <table class="mt-4">
                    <tbody>
                        <tr>
                            <td> Entrada General</td>
                            <td class="pl-8 text-right"> $150.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Nacionales</td>
                            <td class="text-right"> $100.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Residentes de Yucatán</td>
                            <td class="text-right"> $50.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Menores 0-3 años</td>
                            <td class="text-right"> $0.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Menores 4-12 años</td>
                            <td class="text-right"> $25.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Menores 13-17 años</td>
                            <td class="text-right"> $50.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Maestros y estudiantes</td>
                            <td class="text-right"> $25.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Adultos mayores (INAPAM)</td>
                            <td class="text-right"> $25.00 MXN </td>
                        </tr>
                        <tr>
                            <td> Personas con discapacidad</td>
                            <td class="text-right"> $25.00 MXN </td>
                        </tr>
                    </tbody>
                </table>
                <p class="mt-4">* Acreditar a través de documento oficial vigente (INE, licencia de conducir, pasaporte,
                    INAPAM, credencial de maestro o estudiante) presentado físicamente.</p>

                <h5 class="mt-4 text-gray-600 font-semibold"> Martes </h5>
                <p class="mt-2">
                    Entrada libre para residentes de Yucatán al presentar físicamente documento oficial
                    vigente (INE, licencia de conducir o pasaporte). Los menores de edad que acompañen
                    a los acreditados entrarán gratis.
                </p>

                <h5 class="mt-4 text-gray-600 font-semibold">Horario</h5>
                <div class="whitespace-pre-line">{{setting('horario','Martes a domingo de 10:00 a.m. a 4:00 p.m.')}}</div>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/palacio.blade.php
@extends('layouts.app')

@section('header')
<header class="h-100 bg-cover bg-no-repeat bg-center" style="background-image: url({{url('storage/images/slidePalacioMusica-03.jpg')}})">
</header>
@endsection

@section('content')
<div class="flex flex-col lg:flex-row container mx-auto ">
    <section class="lg:w-1/2 px-6">
        <div class="pt-8">
            <h2 class="text-2xl text-gray-900 uppercase">Palacio de la Música</h2>
            <h3 class="text-2xl text-palam-500 font-bold uppercase ">Centro nacional de la música mexicana </h3>
            <p class="mt-4 antialiased">
                El diseño arquitectónico del edificio que alberga el Palacio de la Música fue resultado de los trabajos
                realizados por Alejandro Medina Arquitectura, Reyes Ríos + Larraín Arquitectos, Muñoz Arquitectos y
                Quesnel
                Arquitectos y un amplio equipo de especialistas en el diseño y construcción de obra pública.
            </p>
            <p class="mt-4 antialiased">
                Es un edificio moderno que se inserta de manera sensible en el centro histórico de la ciudad de Mérida,
                Yucatán. Y destaca por dos criterios arquitectónicos de gran valor: el respeto a su entorno y su
                vocación social. <br>
                Las características del inmueble del Palacio de la Música muestran el interés fundamental de contribuir
                a la revitalización del espacio urbano, a través de la permeabilidad visual y conectividad peatonal, y
                fortalecer el sentido de pertenencia de la ciudadanía, tanto con el Palacio de la Música, como con el
                centro
                histórico de Mérida, Yucatán.
            </p>
        </div>
        <div class="pt-8">
            <h3 class="text-2xl text-palam-500 font-bold uppercase">Vision</h3>
            <p class="mt-4 antialiased">
                Ser el principal referente nacional e internacional acerca de la música tradicional y popular mexicana.
            </p>
        </div>
        <div class="pt-8">
            <h3 class="text-2xl text-palam-500 font-bold uppercase">Misión</h3>
            <p class="mt-4 antialiased">
                Presentar el panorama general de la música tradicional y popular mexicana para poner en valor, conservar
                y difundir, entre el público nacional y extranjero, su importancia como patrimonio cultural inmaterial;
                a través de una propuesta atractiva y amena que propicie el conocimiento, la emotividad y el
                entretenimiento de los más diversos visitantes.
            </p>
        </div>
    </section>
    <div class="lg:w-1/2 lg:flex lg:flex-col-reverse">
        <div class="flex flex-row lg:flex-col items-end lg:items-start lg:ml-6">
            <div class="mt-4">
                <img class="" src="{{asset('storage/images/ninaInteractivo-Palacio-Musica.png')}}" alt="">
            </div>
            <div class="mt-4">
                <img class="" src="{{asset('storage/images/salaConciertos-Palacio-Musica.png')}}" alt="">
            </div>
        </div>
        <section class="container mx-auto px-6 lg:mt-10">
            <div class="pt-8">
                <h3 class="text-2xl text-palam-500 font-bold uppercase">Espacios y servicios </h3>
                <p class="mt-4 antialiased">
                    El Palacio de la Música enfoca su labor en la preservación y divulgación de la música tradicional y
                    popular mexicana, por lo cual ofrece diferentes espacios y servicios dedicados al conocimiento y
                    disfrute de nuestro maravilloso patrimonio musical.
                </p>
                <ul class="mt-4 pl-4">
                    <li> Museo </li>
                    <li> Sala de conciertos </li>
                    <li> Acceso a la Red Nacional de Fonotecas </li>
                    <li> Eventos culturales </li>
                </ul>
            </div>
            <div class="pt-8">
                <h3 class="text-2xl text-palam-500 font-bold uppercase">SALA DE CONCIERTOS</h3>
                <p class="mt-4 antialiased">
                    La sala de conciertos tiene capacidad para 458 personas y cuenta con equipos de alta tecnología que
                    hacen posible llevar a cabo presentaciones musicales de primer nivel, así como charlas,
                    conferencias,
                    seminarios y actividades de distinta índole. Además de tener la posibilidad de funcionar como
                    estudio de
                    grabación.
                </p>
            </div>
            <div class="pt-8">
                <h3 class="text-2xl text-palam-500 font-bold uppercase">RED NACIONAL DE FONOTECAS </h3>
                <p class="mt-4 antialiased">
                    La Red Nacional de Fonotecas tiene una plataforma tecnológica que permite acceder al sistema de
                    consulta
                    del patrimonio sonoro digitalizado de la Fonoteca Nacional.
                </p>
            </div>
        </section>
    </div>
</div>
<div class="mt-8">
    <img class="w-full h-auto" src="{{asset('storage/images/Vista-Palacio-Musica.png')}}" alt="">
</div>
@endsection

resources/views/post.blade.php
@extends('layouts.app')

@section('header')
@if($post)
<div class="mt-32"></div>
@else
<header class="h-80 bg-cover bg-no-repeat bg-center"
    style="background-image: url({{url('storage/images/press-mic.jpg')}})">
</header>
@endunless
@endsection

@section('content')

<section class="container mx-auto pt-6 pb-8 px-6">
    <h4 class="text-2xl uppercase"> Palacio de la Música </h4>

    @if($post)
    <article class="">
        <h2 class="text-2xl uppercase text-palam-500 font-bold mt-4"> <a
                href="{{url($section->slug)}}">{{$section->name}}
            </a></h2>
        <div class="flex flex-col lg:flex-row items-center">
            <div class="mt-4">
                <h1 class="text-2xl uppercase text-palam-500 font-bold">{{$post->title}}</h1>
                <h2 class="text-gray-900 text-sm">{{$post->description}}</h2>
            </div>
            <div class="mt-4 lg:ml-4">
                <img class="w-full" src="{{url("storage/{$post->filename}")}}" alt="{{$post->title}}">
                <div class="mt-6 text-gray-800 antialiased">
                    {!! $post->content !!}
                </div>
            </div>
        </div>
    </article>

    @else

    <h1 class="text-2xl uppercase text-palam-500 font-bold"> {{$section->name}} </h1>
    <div class="flex flex-col lg:flex-row lg:flex-wrap justify-between">
        @forelse($section->posts()->latest()->get() as $p)
        <div class="lg:w-5/12">
            <div class="py-8">
                <a href="{{route('post',['section'=>$section->slug,'post'=>$p->slug])}}">
                    <img class="w-full" src="{{url($p->filename)}}" alt="{{$p->title}}">
                </a>
            </div>
            <h2 class="text-palam-500 uppercase font-bold">
                <a href="{{route('post',['section'=>$section->slug,'post'=>$p->slug])}}">
                    {{$p->title}}
                </a>
            </h2>
            <h3> {{$p->description}} </h3>
        </div>
        @empty
        <div>
            Proximamente
        </div>
        @endforelse
    </div>
    @endif

</section>
@endsection

resources/views/press.blade.php
@extends('layouts.app')

@section('header')
<header class="h-100 bg-cover bg-no-repeat bg-center" style="background-image: url({{url('storage/images/slidePalacioMusica-01.jpg')}})"></header>
@endsection

@section('content')
Prensa

@endsection

resources/views/sound-library.blade.php
@extends('layouts.app')

@section('header')
<header class="h-80 bg-cover bg-no-repeat bg-center" style="background-image: url({{url('storage/images/slidePalacioMusica-01.jpg')}})"> </header>
@endsection

@section('content')

<div class="flex flex-col lg:flex-row container mx-auto h-screen">
    <section class="px-6 my-4">
        <h4 class="mt-4 text-2xl text-gray-900 uppercase"> FONOTECA PRÓXIMAMENTE </h4>

        <p class="mt-4">
            La fonoteca del Palacio de la Música es un espacio físico donde se encuentran terminales de cómputo conectadas al sistema de consulta de audios de la Fonoteca Nacional y que tiene como finalidad acercar al público a una parte fundamental de la herencia cultural de la nación: el patrimonio sonoro, y a la vez busca fomentar la cultura de la escucha en la comunidad donde se instala.
        </p>

    </section>
</div>

@endsection

resources/views/trans.blade.php
@extends('layouts.app')

@section('header')
<header class="h-100 md:h-140 lg:h-180 bg-cover bg-no-repeat bg-center" style="background-image: url({{url('storage/images/slidePalacioTrans.jpg')}})">
    <div class="container mx-auto flex flex-col lg:flex-row h-full items-center lg:justify-around justify-center">
        <div class="mt-4">
            <a class="uppercase text-white" target="_blank" href="https://www.plataformadetransparencia.org.mx/web/guest/inicio">
                Plataforma nacional de transparencia
            </a>

        </div>
        <div class="mt-4">
            <a class="uppercase text-white" href="{{route('accounting')}}">
                Contabilidad gubernamental
            </a>
        </div>
        <div class="mt-4">
            <a class="uppercase text-white" target="_blank" href="https://consultapublicamx.inai.org.mx/vut-web/faces/view/consultaPublica.xhtml#sujetosObligados">
                Plataforma estatal de transparencia
            </a>
        </div>
    </div>
</header>
@endsection

@section('content')
@endsection